# Generated by Django 6.0.5 on 2026-06-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='crated_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='message',
        ),
    ]
